cache:
  key: "sscrypto" # universal cache
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

.test-node: &test-node
  stage: test
  script:
    - npm run coverage
  artifacts:
    name: "sscrypto_coverage_${CI_BUILD_ID}_${CI_BUILD_REF}"
    when: always
    expire_in: 1 mos
    paths:
    - coverage/

test-node-10:
  image: node:10
  <<: *test-node

test-node-12:
  image: node:12
  <<: *test-node

test-browser:
  image: nexus-docker.tardis.seald.io/seald/docker-browser-testing:CHROME_76
  stage: test
  script:
    - npm run test-browser

.deploy:
  image: node:10
  stage: deploy
  script:
    - npm run build
    - npm publish
  only:
    - tags
